### ISSUE TITLE
[BUG] mirai报错：NetworkHandler is already closed.

### ISSUE THREAD

**Issue by scanfzq** [RockChinQ/qcg-installer#14]
**Windows**
- 部署方式：
    自动部署
- 系统环境：
    WIndows 10 专业版 x64
**描述漏洞**
运行主程序登陆成功后用QQ发送消息未收到回复
**解决办法**
推测是网络问题，重新关闭mirai和主程序并重新登录启动

**完整报错信息**
![IMG_20221216_173916.jpg](https://user-images.githubusercontent.com/97910358/208069510-274825bc-db6e-4c0e-b82f-1850f6716ecf.jpg)
![46e1148fa1c79109.jpg](https://user-images.githubusercontent.com/97910358/208069546-9db6f409-ee7f-478d-a17b-20832478cfe1.jpg)

**Comment by RockChinQ** [comment]
报错那张图贴一下吧
