### ISSUE TITLE
[BUG]启动run-bot.bat闪退，命令行运行报错

### ISSUE THREAD

**Issue by lingyunytc** [RockChinQ/qcg-installer#15]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    Windows 2022
- Python环境（仅手动部署填写）：
   Python 3.10.9

**描述漏洞**
命令行运行run-bot.bat

**完整报错信息**
![~~)J((V }LDJ{HE J}KPF4M](https://user-images.githubusercontent.com/61460076/208100337-71b6c0e2-8e9b-44b7-902c-65aa8819940d.png)

**Comment by HelloFancyWorld** [comment]
我是这样才对
/python/Scripts/pip3.exe install pymysql yiri-mirai openai colorlog func_timeout
/python/Scripts/pip3.exe install websockets --upgrade

**Comment by HelloFancyWorld** [comment]
我是这样才对
`
/python/Scripts/pip3.exe install pymysql yiri-mirai openai colorlog func_timeout
`
`
/python/Scripts/pip3.exe install websockets --upgrade
`

**Comment by JjiahanH** [comment]
你好，怎么处理No module named 'pip'问题

**Comment by RockChinQ** [comment]
> 你好，怎么处理No module named 'pip'问题

有什么报错信息

**Comment by JjiahanH** [comment]
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的\python\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'

> > 你好，怎么处理No module named 'pip'问题
> 
> 有什么报错信息

**Comment by RockChinQ** [comment]
> Traceback (most recent call last): File "runpy.py", line 196, in _run_module_as_main File "runpy.py", line 86, in _run_code File "C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的\python\Scripts\pip.exe__main__.py", line 4, in ModuleNotFoundError: No module named 'pip'
> 
> > > 你好，怎么处理No module named 'pip'问题
> > 
> > 
> > 有什么报错信息

检查python下是否有Scripts目录，若没有请先查看https://github.com/RockChinQ/qcg-installer/issues/21

**Comment by JjiahanH** [comment]
> > Traceback (most recent call last): File "runpy.py", line 196, in _run_module_as_main File "runpy.py", line 86, in _run_code File "C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的\python\Scripts\pip.exe__main__.py", line 4, in ModuleNotFoundError: No module named 'pip'
> > > > 你好，怎么处理No module named 'pip'问题
> > > 
> > > 
> > > 有什么报错信息
> 
> 检查python下是否有Scripts目录，若没有请先查看#21

你好，是在进行过这个步骤后出现的这个

**Comment by RockChinQ** [comment]
> > > Traceback (most recent call last): File "runpy.py", line 196, in _run_module_as_main File "runpy.py", line 86, in _run_code File "C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的\python\Scripts\pip.exe__main__.py", line 4, in ModuleNotFoundError: No module named 'pip'
> > > > > 你好，怎么处理No module named 'pip'问题
> > > > 
> > > > 
> > > > 有什么报错信息
> > 
> > 
> > 检查python下是否有Scripts目录，若没有请先查看#21
> 
> 你好，是在进行过这个步骤后出现的这个

是正在进行此步骤时发生的？把你执行指令前后的命令行输出多贴一点出来

**Comment by JjiahanH** [comment]
C:\Users\贾涵>cd C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的

C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的>cd python

C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的\python>python.exe get-pip.py
Collecting pip
  Using cached pip-22.3.1-py3-none-any.whl (2.1 MB)
Collecting setuptools
  Using cached setuptools-65.7.0-py3-none-any.whl (1.2 MB)
Collecting wheel
  Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
Installing collected packages: wheel, setuptools, pip
Successfully installed pip-22.3.1 setuptools-65.7.0 wheel-0.38.4

C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的\python>cd ..                                                                 
C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的>python\Scripts\pip.exe install pymysql yiri-mirai openai colorlog func_timeout
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的\python\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'

C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的>

**Comment by JjiahanH** [comment]
麻烦了

**Comment by RockChinQ** [comment]
> ```
> C:\Users\贾涵>cd C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的
> 
> C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的>cd python
> 
> C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的\python>python.exe get-pip.py
> Collecting pip
>   Using cached pip-22.3.1-py3-none-any.whl (2.1 MB)
> Collecting setuptools
>   Using cached setuptools-65.7.0-py3-none-any.whl (1.2 MB)
> Collecting wheel
>   Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
> Installing collected packages: wheel, setuptools, pip
> Successfully installed pip-22.3.1 setuptools-65.7.0 wheel-0.38.4
> 
> C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的\python>cd ..                                                                 
> C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的>python\Scripts\pip.exe install pymysql yiri-mirai openai colorlog func_timeout
> Traceback (most recent call last):
>   File "runpy.py", line 196, in _run_module_as_main
>   File "runpy.py", line 86, in _run_code
>   File "C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的\python\Scripts\pip.exe\__main__.py", line 4, in <module>
> ModuleNotFoundError: No module named 'pip'
> 
> C:\Users\贾涵\Desktop\压缩包\压缩包\电脑的>
> ```

可能是由于电脑上本身装有Python环境，导致自动部署冲突，建议你尝试 [进行手动部署](https://github.com/RockChinQ/QChatGPT#--%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2)

**Comment by JjiahanH** [comment]
好的谢谢啦

**Comment by YuanyiZhezhi11** [comment]
在安装器同目录执行指令要怎么做，我一打开就闪退了

**Comment by YuanyiZhezhi11** [comment]
要怎么切换，安装器是mirai吗

**Comment by RockChinQ** [comment]
> 要怎么切换，安装器是mirai吗

命令行使用方法请自行搜索了解；你需要在qcg-installer的同目录执行这些命令

**Comment by YuanyiZhezhi11** [comment]
系统找不到指定的路径，是要在cmd里打开到同目录吗，我不太会弄抱歉

**Comment by YuanyiZhezhi11** [comment]
现在我这边显示无法完成操作 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。在cmd中

**Comment by RockChinQ** [comment]
> 系统找不到指定的路径，是要在cmd里打开到同目录吗，我不太会弄抱歉

如果你是Windows 10系统，你可以直接打开到qcg-installer同目录之后，按住`shift`的同时在空白处右键，点击`在此处打开Powershell`或相似条目，在打开的命令行窗口中输入以上要求的指令；如果此打开命令行的方法不可用，请根据刚刚这个知乎文章打开命令行，使用`cd`命令切换到目标目录再执行

**Comment by RockChinQ** [comment]
> 现在我这边显示无法完成操作 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。在cmd中

有报错发截图

**Comment by YuanyiZhezhi11** [comment]
![image](https://user-images.githubusercontent.com/114741580/213171837-64ebb46e-71f9-4532-85e4-244376a65e67.png)

**Comment by RockChinQ** [comment]
> ![image](https://user-images.githubusercontent.com/114741580/213171837-64ebb46e-71f9-4532-85e4-244376a65e67.png)

这个我没法提供解决方案，建议你关闭电脑上所有杀毒软件

**Comment by YuanyiZhezhi11** [comment]
本机的安全防护要怎么关

**Comment by YuanyiZhezhi11** [comment]
![IMG_20230118_205635.jpg](https://user-images.githubusercontent.com/114741580/213177260-45bf1fe7-4fc0-49a6-98eb-259bd8b6ed82.jpg)如果是自动安装的话也会弹出这样的情况

**Comment by YuanyiZhezhi11** [comment]
无法连接到mirai服务器怎么办

**Comment by DevilCoke1** [comment]
> 
 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /packages/57/6d/1ba9762f7caf4f2cf8bdd268087e4ea6c9a83f197f5c2afc06ff0812a846/yiri_mirai-0.2.6.1-py3-none-any.whl
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/57/6d/1ba9762f7caf4f2cf8bdd268087e4ea6c9a83f197f5c2afc06ff0812a846/yiri_mirai-0.2.6.1-py3-none-any.whl (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

**Comment by DevilCoke1** [comment]
> 

这个跟梯子有问题，把梯子关了就可以。

**Comment by DevilCoke1** [comment]
![image](https://user-images.githubusercontent.com/77016025/222184319-0f3af30d-43e0-4e62-9056-beb642daebeb.png)
![1](https://user-images.githubusercontent.com/77016025/222184686-dbf8cb98-5c8f-4227-a2c8-c05992d463d2.png)
