### ISSUE TITLE
[BUG]安装器提示输入的apikey不符合格式要求

### ISSUE THREAD

**Issue by unsignedzhang** [RockChinQ/qcg-installer#18]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    e,g,winserver 2012

**描述漏洞**
安装器提示输入的apikey不符合格式要求，但我确实是从官网复制的

**完整报错信息**
完整的报错信息

**Comment by RockChinQ** [comment]
应该是bug，请先按照[这个方法](https://github.com/RockChinQ/qcg-installer/issues/17)手动设置apikey完成配置
