### ISSUE TITLE
[BUG] 主程序启动时提示No module named，检查发现Python目录下无Scripts目录

### ISSUE THREAD

**Issue by RockChinQ** [RockChinQ/qcg-installer#21]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    Windows

**Comment by Sncky** [comment]
D:\>QQchat\python\python get-pip.py
拒绝访问。

D:\>QQchat\python\python get-pip.py
拒绝访问。
坏了，人家不要我。

**Comment by kizaniver** [comment]
![image](https://user-images.githubusercontent.com/106379728/219936880-e0ff743a-13df-4e81-a843-14d7366cf6c9.png)
这是什么情况

**Comment by RockChinQ** [comment]
> ![image](https://user-images.githubusercontent.com/106379728/219936880-e0ff743a-13df-4e81-a843-14d7366cf6c9.png) 这是什么情况

#15
