### ISSUE TITLE
[BUG] /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by Henry14all** [RockChinQ/qcg-installer#23]
**运行环境**
- 部署方式：自动部署

- 系统环境：
    Ubuntu 20.04 LTS

**描述漏洞**
When I try to run "sudo ./qcg-installer-linux-amd64",then it return a "GLIBC_2.3* not found". 

**完整报错信息**
```
./qcg-installer-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./qcg-installer-linux-amd64)
./qcg-installer-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./qcg-installer-linux-amd64)
```

**Comment by RockChinQ** [comment]
python编译安装失败，缺少编译环境组件，建议手动部署

**Comment by Henry14all** [comment]
> python编译安装失败，缺少编译环境组件，建议手动部署

我不是非常了解Python，所以我希望您能介绍一下为什么自动部署仍需要安装Python

![image](https://user-images.githubusercontent.com/59821569/211330807-fcd1b952-e2d6-4def-bc23-2cb47a65fc6b.png)

**Comment by RockChinQ** [comment]
主程序依赖于Python环境运行，所以需要配置Python环境。你可以按照网上的Linux系统下Python环境安装教程自行配置Python以通过手动部署的方式使用此程序，手动部署的步骤见[主程序文档](https://github.com/RockChinQ/QChatGPT#--%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2)

**Comment by Henry14all** [comment]
> 主程序依赖于Python环境运行，所以需要配置Python环境。你可以按照网上的Linux系统下Python环境安装教程自行配置Python以通过手动部署的方式使用此程序，手动部署的步骤见[主程序文档](https://github.com/RockChinQ/QChatGPT#--%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2)

好的，谢谢你
