### ISSUE TITLE
[BUG] 新用户未曾使用过，生成api-key显示额度超限

### ISSUE THREAD

**Issue by lijie-jie** [RockChinQ/qcg-installer#27]
**运行环境**
- 部署方式：
    手动部署
- 系统环境：
    e,g, Windows 10
- Python环境：
    e.g. Python 3.10.9

**描述漏洞**
新用户未曾使用过，生成api-key显示额度超限，在QChatGPT文件夹的config.py中配置了api-key，是目前已经无法使用此方法了吗？

**完整报错信息**

[bot]api-key调用额度超限(default),无可用api_key,请向OpenAI账户充值或在config.py中更换api_key

**Comment by Mr-yf-shui** [comment]
同问

**Comment by RockChinQ** [comment]
自行到openai官网查询你的额度，没有那就是没有了

**Comment by Mr-yf-shui** [comment]
> 自行到openai官网查询你的额度，没有那就是没有了

啊o(≧口≦)o 我刚刚注册啊【绝望.jpg】
