### ISSUE TITLE
获得的api是达芬奇3？

### ISSUE THREAD

**Issue by KingSF5** [RockChinQ/qcg-installer#28]
达芬奇3貌似是基于gpt3.0的，chatgpt现在还没有api？

**Comment by RockChinQ** [comment]
> 达芬奇3貌似是基于gpt3.0的，chatgpt现在还没有api？

敏锐的观察力。目前只能使用官方的api调用gpt3模型，chatgpt还没有官方接口，为保证稳定性，本项目不会在主分支中接入chatgpt逆向库。

**Comment by KingSF5** [comment]
> > 达芬奇3貌似是基于gpt3.0的，chatgpt现在还没有api？
> 
> 敏锐的观察力。目前只能使用官方的api调用gpt3模型，chatgpt还没有官方接口，为保证稳定性，本项目不会在主分支中接入chatgpt逆向库。

好的 感谢
