### ISSUE TITLE
[BUG] run-miral后报错 unable to access jarfile mcl.jar 

### ISSUE THREAD

**Issue by guge2** [RockChinQ/qcg-installer#30]
**运行环境**
- 部署方式：
    自动部署

**描述漏洞**
运行run-miral.bat后报错 unable to access jarfile mcl.jar 

**完整报错信息**
C:\Users\abc\Desktop\mirai>java\bin\java -jar mcl.jar
Error: Unable to access jarfile mcl.jar

**Comment by RockChinQ** [comment]
mirai安装过程失败，可以根据主仓库的[手动部署mirai](https://github.com/RockChinQ/QChatGPT#%E9%85%8D%E7%BD%AEmirai)步骤自行配置mirai后使用
