### ISSUE TITLE
不了解如何在Linux运行安装器

### ISSUE THREAD

**Issue by Gloridust** [RockChinQ/qcg-installer#37]
我尝试在centos用安装器安装，但是不了解如何运行安装器的可执行文件。
我尝试了bash，uzip等但不局限于以下以下：
[root@v gptq]# /qcg-installer-linux-amd64
-bash: /qcg-installer-linux-amd64: No such file or directory
[root@v gptq]# ./qcg-installer-linux-amd64
-bash: ./qcg-installer-linux-amd64: Permission denied

希望有大佬能够帮助，并且建议在readme列出安装命令，谢谢帮助
![Uploading EEE0F468-3EA9-4093-93B8-0BFA7C535780.jpeg…]()

**Comment by RockChinQ** [comment]
```bash
chmod +x qcg-installer-linux-amd64
./qcg-installer-linux-amd64
```
