### ISSUE TITLE
安装器运行报错

### ISSUE THREAD

**Issue by Gloridust** [RockChinQ/qcg-installer#38]
**运行环境**
- 部署方式：自动部署
- 系统环境：Centos 64

**描述漏洞**
使用安装器自动安装，运行后立即出现报错

**完整报错信息**
[root@v ~]# cd ./gptq
[root@v gptq]# ./qcg-installer-linux-amd64
./qcg-installer-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./qcg-installer-linux-amd64)
./qcg-installer-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./qcg-installer-linux-amd64)

**Comment by RockChinQ** [comment]
建议手动部署或docker部署，你这个系统环境不适合自动安装
