### ISSUE TITLE
Error(bot=Bot(961471523), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反 馈与我们联系。, errorInfo=)

### ISSUE THREAD

**Issue by JJplane** [RockChinQ/qcg-installer#39]
![image](https://user-images.githubusercontent.com/28783826/227723398-668518f8-7ba0-4467-ad18-05f2edeb43e4.png)

**Comment by RockChinQ** [comment]
https://github.com/RockChinQ/QChatGPT/issues/285
