### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Yanyusama** [RockChinQ/qcg-installer#40]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    windows x64

**描述漏洞**
在运行run.bot.bat报错

**完整报错信息**

D:\QQchatGPT>cd QChatGPT

D:\QQchatGPT\QChatGPT>..\python\python.exe main.py
Traceback (most recent call last):
  File "D:\QQchatGPT\QChatGPT\main.py", line 27, in <module>
    import pkg.utils.context
ModuleNotFoundError: No module named 'pkg'

D:\QQchatGPT\QChatGPT>pause
请按任意键继续. . .
![image](https://user-images.githubusercontent.com/120467373/227723505-846425ec-1cb9-4f61-9ed9-8ee44d51a71c.png)
![image](https://user-images.githubusercontent.com/120467373/227723521-87352250-a70c-45e7-9d9d-0ffdd31e88c6.png)

**Comment by RockChinQ** [comment]
https://github.com/RockChinQ/QChatGPT/issues/305  
主机上python环境复杂，请使用主程序仓库文档中的手动部署步骤进行部署
