### ISSUE TITLE
[enhan]

### ISSUE THREAD

**Issue by YJieKe** [RockChinQ/qcg-installer#48]
想写啥都行
![image](https://github.com/RockChinQ/qcg-installer/assets/105770054/2df289d5-30df-4bba-8f64-09f6ae859044)
我发现的的问题由当前QQ版本版本过低变成了网络不稳定，我不知道这是怎么回事，我需要帮助

**Comment by RockChinQ** [comment]
这个是 mirai 的问题，请前往 https://github.com/mamoe/mirai 寻求帮助

**Comment by RockChinQ** [comment]
这个是 mirai 的问题，请前往 https://github.com/mamoe/mirai 寻求帮助

**Comment by YJieKe** [comment]
首先我感谢你的回信，给我带来了一定的帮助，但是我并没有在上面找到可能帮助到我的内容，出现在答案中的回答都很模糊，我想这应该不足以解决我的问题




化学不上八十不改名
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RockChinQ/qcg-installer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月26日(星期二) 晚上7:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RockChinQ/qcg-installer] [enhan] (Issue #48)





 
这个是 mirai 的问题，请前往 https://github.com/mamoe/mirai 寻求帮助

**Comment by RockChinQ** [comment]
https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88
