### ISSUE TITLE
[BUG]mcl下载失败

### ISSUE THREAD

**Issue by suixiaowen** [RockChinQ/qcg-installer#9]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    Centos x64
- Python环境（仅手动部署填写）：
    Python 3.10.9

**描述漏洞**
什么时候发生的，mirai还是主程序，越详细越好

**完整报错信息**
完整的报错信息

**Comment by RockChinQ** [comment]
计划添加支持手动下载所需文件的功能

**Comment by RockChinQ** [comment]
已支持使用手动下载的安装文件
